### ISSUE TITLE
Microsoft.Web/sites properties noise

### ISSUE THREAD

**Issue by fulder** [Azure/arm-template-whatif#131] opened 2020-10-01 11:06 UTC
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Web/sites

**apiVersion** (i.e. 2019-04-01)
2018-11-01

**Client (PowerShell, Azure CLI, or API)**
Azure CLI

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
{
      "type": "Microsoft.Web/sites",
      "apiVersion": "2018-11-01",
      "name": "[parameters('functionAppName')]",
      "location": "North Europe",
      "kind": "functionapp,linux",
      "properties": {
        "enabled": true,
        "hostNameSslStates": [
          {
            "name": "[concat(parameters('functionAppName'), '.azurewebsites.net')]",
            "sslState": "Disabled",
            "hostType": "Standard"
          },
          {
            "name": "[concat(parameters('functionAppName'), '.scm.azurewebsites.net')]",
            "sslState": "Disabled",
            "hostType": "Repository"
          }
        ],
        "serverFarmId": "<SWARM_FARM_ID>",
        "reserved": true,
        "isXenon": false,
        "hyperV": false,
        "siteConfig": {
          "appSettings": [
            {
              "name": "AzureWebJobsStorage",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('storageAccountName'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')),providers('Microsoft.Storage', 'storageAccounts').apiVersions[0]).keys[0].value)]"
            },
            {
              "name": "AzureWebJobsDashboard",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('storageAccountName'), ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')),providers('Microsoft.Storage', 'storageAccounts').apiVersions[0]).keys[0].value)]"
            },
            {
              "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
              "value": "[reference(resourceId('Microsoft.Insights/components/', parameters('functionAppName')), '2015-05-01').InstrumentationKey]"
            },
            {
              "name": "FUNCTIONS_EXTENSION_VERSION",
              "value": "~3"
            },
            {
              "name": "FUNCTIONS_WORKER_RUNTIME",
              "value": "python"
            }
          ],
          "http20Enabled": true,
          "localMySqlEnabled": false,
          "netFrameworkVersion": "v4.6"
        },
        "scmSiteAlsoStopped": false,
        "clientAffinityEnabled": false,
        "clientCertEnabled": false,
        "hostNamesDisabled": false,
        "containerSize": 1536,
        "dailyMemoryTimeQuota": 0,
        "httpsOnly": true,
        "redundancyMode": "None"
      }
    }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No noise for the siteConfig properties after first time this ARM resource got deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
```
~ Microsoft.Web/sites/<FUNCTION_NAME> [2018-11-01]
    + properties.siteConfig.http20Enabled:       true
    + properties.siteConfig.localMySqlEnabled:   false
    + properties.siteConfig.netFrameworkVersion: "v4.6"
```

**Comment by alex-frankel** [comment] 2020-10-01 22:11
Closing as duplicate of #90

**Closed by alex-frankel** 2020-10-01 22:11 UTC
Labels: provider bug
