### ISSUE TITLE
Microsoft.Web/sites/config connectionstrings

### ISSUE THREAD

**Issue by devnomadic** [Azure/arm-template-whatif#73] opened 2020-05-25 06:11 UTC
### **Describe the noise**
Getting the following error when using Get-AzResourceGroupDeploymentWhatIfResult

```
{
    "Code": "DeploymentWhatIfResourceError",
    "Message": "The request to predict template deployment changes to subscription 'xxx' and resource group 'xx' has failed due to a resource error. See details for more information.",
    "Target": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Web/sites/xxx/config/connectionstrings?api-version=2019-08-01",
    "Details": [
      {
        "Code": "DeploymentWhatIfResourceInvalidResponse",
        "Message": "The request '/subscriptions/xxx/resourceGroupsxxx/providers/Microsoft.Web/sites/xxx/config/connectionstrings?api-version=2019-08-01' resulted in an unexpected HTTP status code 'MethodNotAllowed'. Diagnostic information: timestamp '20200525T055352Z', tracking id 'd661b992-d491-4eaa-961f-2ddad125ed43', request correlation id '7da8b3fa-6c24-49e4-918f-9cc66beb7d97', location 'australiaeast'.",
        "Target": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Web/sites/xxx/config/connectionstrings?api-version=2019-08-01",
        "Details": [],
        "AdditionalInfo": []
      }
    ],
    "AdditionalInfo": []
  }
```

**Resource type:**
Microsoft.Web/sites/config

**apiVersion:**
2019-08-01

**Client:**
PowerShell

**Relevant ARM Template code:**

```
{
        "apiVersion": "2016-08-01",
        "type": "Microsoft.Web/sites",
        "kind": "app",
        "name": "[concat(parameters('svcPlanName'), '-', parameters('WebApps')[copyIndex()], '-', parameters('AzureRegion'))]",
        "location": "[resourceGroup().location]",
        "identity": {
          "type": "SystemAssigned, UserAssigned",
          "userAssignedIdentities": {
            "[resourceId(parameters('KeyVaultResourceGroup'), 'Microsoft.ManagedIdentity/userAssignedIdentities', parameters('UserIdentity'))]": {}
          }
        },
        "copy": {
          "name": "WebAppcopy",
          "count": "[length(parameters('WebApps'))]"
        },
        "properties": {
          "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', concat(parameters('svcPlanName'), '-', parameters('AzureRegion')))]",
          "httpsOnly": true
        },
        "dependsOn": [
          "[resourceId('Microsoft.Web/serverfarms',concat(parameters('svcPlanName'), '-', parameters('AzureRegion')))]",
          "[resourceId('Microsoft.Insights/components', concat(parameters('svcPlanName'), '-', parameters('WebApps')[copyIndex()], '-', parameters('AzureRegion')))]"
        ],
        "resources": [
          {
            "apiVersion": "2019-08-01",
            "type": "config",
            "name": "connectionstrings",
            "dependsOn": [
              "[concat('Microsoft.Web/sites/', concat(parameters('svcPlanName'), '-', parameters('WebApps')[copyIndex()], '-', parameters('AzureRegion')))]"
            ],
            "properties": {
              "CMSConnectionString": {
                "value": "[concat('@Microsoft.KeyVault(SecretUri=', reference(resourceId(parameters('KeyVaultResourceGroup'), 'Microsoft.KeyVault/vaults/secrets', parameters('KeyVaultName'), parameters('CMSConnectionStringSecretName')), '2018-02-14').secretUriWithVersion, ')')]",
                "type": "SQLServer"
              },
              "CMSOMConnectionString": {
                "value": "[concat('@Microsoft.KeyVault(SecretUri=', reference(resourceId(parameters('KeyVaultResourceGroup'), 'Microsoft.KeyVault/vaults/secrets', parameters('KeyVaultName'), parameters('CMSOMConnectionStringSecretName')), '2018-02-14').secretUriWithVersion, ')')]",
                "type": "SQLServer"
              },
              "AIHWSessionState": {
                "value": "[concat('@Microsoft.KeyVault(SecretUri=', reference(resourceId(parameters('KeyVaultResourceGroup'), 'Microsoft.KeyVault/vaults/secrets', parameters('KeyVaultName'), parameters('SessionConnectionStringSecretName')), '2018-02-14').secretUriWithVersion, ')')]",
                "type": "SQLServer"
              }
            }
          }
```

**Expected response:**
Expected noise

**Additional context**
Connection strings are KeyVault references

**Comment by alex-frankel** [comment] 2020-05-26 21:03
might be related to https://github.com/Azure/arm-template-whatif/issues/65

Can you consistently reproduce this or is the error intermittent?

**Comment by devnomadic** [comment] 2020-05-27 04:49
Hi @alex-frankel I can consistently reproduce the error. I have not been able to successfully run the what-if functions on my appservice template. I have tried different api versions with the same result. I also replaced the keyvault with string values and I still get the same error.

**Comment by alex-frankel** [comment] 2020-05-27 14:43
Thanks - we will investigate

**Comment by alex-frankel** [comment] 2020-05-28 23:03
correlationId: 7da8b3fa-6c24-49e4-918f-9cc66beb7d97

**Comment by JakobGSvendsen** [comment] 2020-07-01 13:22
I have the same issue! :)

**Comment by shenglol** [comment] 2020-07-01 22:20
The root cause is that the RP doesn't allow `GET` method on a web config when the config name is `connectionstring`, because that is a secret.

**Comment by AkhilGNair** [comment] 2020-07-07 09:42
Apologies if it is already know (I don't see it mentioned elsewhere in the issues).

I also see this on `Microsoft.Web/sites/config` `authsettings`.

**Comment by vforteli** [comment] 2020-08-28 17:23
Same issue here with Microsoft.Web/sites/config/appsettings. 
Moving the appsettings directly into the siteconfig of Microsoft.Web/sites works fine, however this is not an option because that would cause a circular dependency with keyvault references in my case.

**Comment by mauve** [comment] 2020-10-05 08:34
I get the same error on the following resource btw:

```json
    {
      "type": "Microsoft.Web/sites/config",
      "apiVersion": "2018-11-01",
      "name": "[concat(variables('frontendAppName'), '/authsettings')]",
      "location": "[resourceGroup().location]",
      "dependsOn": [
        "[concat('Microsoft.Web/sites/', variables('frontendAppName'))]"
      ],
      "properties": {
        "unauthenticatedClientAction": "RedirectToLoginPage",
        "enabled": true,
        "clientId": "REDACTED",
        "issuer": "https://sts.windows.net/REDACTED/"
      }
    },
```

**Comment by FemiaLeandro** [comment] 2020-10-30 19:01
I'm getting the same issue as above, when deploying **appsettings** in the _/sites/config_ resource.

I tested what @vforteli said about moving the appsettings directly into the **siteConfig** of Microsoft.Web/sites and this causes the settings not to be included in the deploy.

**Comment by rchriste** [comment] 2020-12-03 16:35
What I want is for what-if to show this one part as redacted or not comparable in the what-if result but otherwise give an answer. I love the idea that what-if protects me from displaying secrets but I want the rest to work. I want to use the feature.

**Comment by felipe2050** [comment] 2021-01-30 01:37
Any updates about this?

**Comment by shenglol** [comment] 2021-02-13 01:16
The web team is working on fixing the issue now. The ETA for the fix to be rolled out is mid April.

**Comment by mauve** [comment] 2021-03-31 11:16
@shenglol does this mean that we will be able to do what-if deployments if we have `Microsoft.Web/sites/config@VERSION` `authsettings`  in our templates?

**Comment by shenglol** [comment] 2021-04-01 22:20
@mauve Yes, that's correct.

**Comment by mauve** [comment] 2021-04-18 14:42
Hi, do you have a status update?

**Comment by nicolas-martin-dte** [comment] 2021-05-03 21:38
ETA for fix was mid-April, per above, but error is still biting me.

Hoping for a resolution to this (and by extension #65). I am in a similar boat to @vforteli where defining the app settings as a separate resource is necessary to avoid a circular dependency with Key Vault secrets. Despite lots of warnings that `what-if` just 'isn't ready yet' I found it really helpful in other situations. Alas, could use it now and can't. 😢

**Comment by shenglol** [comment] 2021-05-04 18:46
It seems the fix is still not rolled out by the web team. I'll follow up with them and get an updated ETA. In the meantime, we are updating the What-If backend to handle ARM RPC violations gracefully, so that resource types that do not support GET will be reported as "Unsupported".

**Comment by alex-frankel** [comment] 2021-05-13 16:27
Latest ETA is now mid-June.

**Comment by mauve** [comment] 2021-05-17 18:16
@alex-frankel the mid-June ETA, is that for the What-If backend workaround or for proper fix by the WebSites-team

**Comment by alex-frankel** [comment] 2021-05-17 18:23
For the proper fix

**Comment by mickybar** [comment] 2021-06-21 08:31
Any update about this one?

**Comment by mauve** [comment] 2021-06-21 21:43
Any update on this?

**Comment by alex-frankel** [comment] 2021-06-25 16:34
I'm waiting on an update from the web team..

Has anyone attempted to repro recently? It may have been deployed by this point.

**Comment by mickybar** [comment] 2021-06-25 17:07
@alex-frankel when I posted 4 days ago it was because it wasn't working. Didn't retry recently though

**Comment by alex-frankel** [comment] 2021-06-28 21:16
Latest update:

This is rolled out to every region except "south central US". ETA to complete the rollout is 7/2.

**Comment by shenglol** [comment] 2022-04-15 22:52
The fix has been rolled out.

**Closed by shenglol** 2022-04-15 22:52 UTC
Labels: provider bug, write only
