### ISSUE TITLE
Microsoft.ContainerInstance/containerGroups (2018-10-01)

### ISSUE THREAD

**Issue by neilpeterson** [Azure/arm-template-whatif#9] opened 2019-12-02 00:24 UTC
## Describe the noise

**Resource type**

Microsoft.ContainerInstance/containerGroups

**apiVersion**

2018-10-01

**Client (PowerShell, Azure CLI, or API)**

PowerShell

**Relevant ARM Template code**

```
{
	"name": "containerGroup1",
	"type": "Microsoft.ContainerInstance/containerGroups",
	"apiVersion": "2018-10-01",
	"location": "[resourceGroup().location]",
	"properties": {
		"containers": [{
			"name": "nepeters",
			"properties": {
				"image": "neilpeterson/nepetersv1",
				"ports": [{
					"port": 80
				}],
				"resources": {
					"requests": {
						"cpu": 1,
						"memoryInGB": 2
					}
				}
			}
		}],
		"osType": "Linux",
		"ipAddress": {
			"type": "Public",
			"ports": [{
				"protocol": "TCP",
				"port": 80
			}]
		}
	}
}
```

**Expected response**

I expected no noise since the template has not been modified since the resources were deployed.

**Current (noisy) response**

```
Resource and property changes are indicated with these symbols:
  - Delete
  ~ Modify

The deployment will update the following scope:

Scope: /subscriptions/3762d87c-ddb8-425f-b2fc-29e5e859edaf/resourceGroups/aci-whatif

  ~ Microsoft.ContainerInstance/containerGroups/containerGroup1 [2018-10-01]
    - properties.ipAddress.ip: "40.88.23.55"
    ~ properties.containers: [    
      ~ 0:

        - properties.instanceView:

            currentState.startTime: "2019-12-02T00:13:57Z"
            currentState.state:     "Running"

        ~ properties.resources.requests.cpu:        1 => 1
        ~ properties.resources.requests.memoryInGB: 2 => 2

      ]

Resource changes: 1 to modify.
```

**Additional context**

Seems like these two are not necessarily noise as each property is specified in the template. Regardless, the results are erroneous.

```
 ~ properties.resources.requests.cpu:        1 => 1
 ~ properties.resources.requests.memoryInGB: 2 => 2
```

**Comment by shenglol** [comment] 2019-12-02 20:09
@neilpeterson Thanks for the feedback. This is a very interesting one. We'll look into this.

**Comment by shenglol** [comment] 2019-12-02 22:46
The erroneous deltas were caused by type mismatch (double VS. integer).
![image](https://user-images.githubusercontent.com/16367959/69999759-3b7d1500-150e-11ea-8f33-ef0d819a02c1.png)

In the template we used integers, but according to the RP's swagger they should be doubles:
![image](https://user-images.githubusercontent.com/16367959/70000483-f659e280-150f-11ea-8186-b0c217802d9a.png)

@majastrz Looks like we have another edge case to handle...

**Comment by majastrz** [comment] 2020-01-10 05:21
The fix has been deployed to all public regions. @neilpeterson, can you confirm it's working for you?

**Comment by majastrz** [comment] 2020-01-14 21:42
Closing the issue. Please reopen if needed.

**Closed by majastrz** 2020-01-14 21:42 UTC
Labels: bug, fix committed, fix deployed, noise, read only
