### ISSUE TITLE
Microsoft.Network/applicationGateways/providers/diagnosticsettings with no metrics always marked for removal

### ISSUE THREAD

**Issue by fulder** [Azure/arm-template-whatif#110] opened 2020-08-10 13:45 UTC
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Network/applicationGateways/providers/diagnosticsettings

**apiVersion** (i.e. 2019-04-01)
2017-05-01-preview

**Client (PowerShell, Azure CLI, or API)**
Azure CLI 2.10.1

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
{
  "name":"gatewayDiagnosticSettings",
  "type":"Microsoft.Network/applicationGateways/providers/diagnosticsettings",
  "apiVersion":"2017-05-01-preview",
  "dependsOn":[
    "[resourceId('Microsoft.Network/applicationGateways','gatewayName'))]"
  ],
  "properties":{
    "metrics":[],
    "logs":[
      {
        "category":"ApplicationGatewayAccessLog",
        "enabled":true,
        "retentionPolicy":{
          "enabled":true,
          "days":60
        }
      },
      {
        "category":"ApplicationGatewayPerformanceLog",
        "enabled":true,
        "retentionPolicy":{
          "enabled":true,
          "days":60
        }
      },
      {
        "category":"ApplicationGatewayFirewallLog",
        "enabled":true,
        "retentionPolicy":{
          "enabled":true,
          "days":60
        }
      }
    ],
    "workspaceId":"/subscriptions/<SUB_ID>/resourceGroups/<RESOURCE_NAME>/providers/Microsoft.OperationalInsights/workspaces/<WORKSPACE_NAME>"
  }
}
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No noise regarding the diagnostic settings after one successful deployment. 

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
```
~ Microsoft.Network/applicationGateways/dev-consolidation/providers/Microsoft.Insights/diagnosticsettings/gatewayDiagnosticSettings [2017-05-01-preview]
    - properties.metrics: [
        0:
          category:                "AllMetrics"
          enabled:                 false
          retentionPolicy.days:    0
          retentionPolicy.enabled: false
      ]
```

**Comment by shenglol** [comment] 2020-08-11 21:34
Duplicate of https://github.com/Azure/arm-template-whatif/issues/62.

What-If currently has a limitation that it cannot handle array properties accepting partial PUT. For now the best we can do is to fix `enabled`, `retentionPolicy.days` and retentionPolicy.enabled` because they have default values.

**Comment by alex-frankel** [comment] 2020-08-11 22:31
Closing since this is a duplicate.

**Closed by alex-frankel** 2020-08-11 22:31 UTC
Labels: duplicate, partial put
