### ISSUE TITLE
Logic App noise - case sensitive noise

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#55] opened 2020-05-11 09:43 UTC
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
In code

**apiVersion** (i.e. 2019-04-01)
In code

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
It is not public

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No changes for properties.endpointsConfiguration, properties.parameters.webhookUrl, properties.definition.parameters.customerName.type, properties.definition.parameters.tenantId.type, properties.definition.parameters.timeZoneName.type and properties.definition.parameters.webhookUrl.type

endpointsConfiguration is never configured and I suspect is it some read only property. It should not show as modified.

The others are input properties for the Logic App code. The one that is secure string is shown as changed but it should not as the value is the same as before. I suspect because it is a secret somehow it thinks that is changed. Also that value should not be exposed if it is secure string. 

The types of the logic app input parameters are also reported as change for some reason.
**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
Resource and property changes are indicated with these symbols:
  - Delete
  + Create
  ~ Modify
  * Ignore
  = NoChange

The deployment will update the following scopes:

Scope: /subscriptions/<subscription Id>

  = Microsoft.Insights/diagnosticSettings/subscriptionLogsToLogAnalytics-3ea7qjbovitsc [2017-05-01-preview]
  = resourceGroups/<resource group name> [2019-05-01]

Scope: /subscriptions/<subscription Id>/resourceGroups/<resource group name>

~ Microsoft.Logic/workflows/<logic app name> [2017-07-01]
    - properties.endpointsConfiguration:

        connector.outgoingIpAddresses: [
          0:

            address: "<some IP Address range>"

          1:

            address: "<some IP Address>"

          2:

            address: "<some IP Address>"

          3:

            address: "<some IP Address>"

          4:

            address: "<some IP Address>"

        ]
        workflow.accessEndpointIpAddresses: [
          0:

            address: "<some IP Address>"

          1:

            address: "<some IP Address>"

          2:

            address: "<some IP Address>"

          3:

            address: "<some IP Address>"

        ]
        workflow.outgoingIpAddresses: [
          0:

            address: "<some IP Address>"

          1:

            address: "<some IP Address>"

          2:

            address: "<some IP Address>"

          3:

            address: "<some IP Address>"

          4:

            address: "<some IP Address>"

          5:

            address: "<some IP Address>"

          6:

            address: "<some IP Address>"

          7:

            address: "<some IP Address>"

        ]
        + properties.parameters.webhookUrl:

        value: "<webhook URL>"

    ~ properties.definition.parameters.customerName.type: "String" => "string"
    ~ properties.definition.parameters.tenantId.type:     "String" => "string"
    ~ properties.definition.parameters.timeZoneName.type: "String" => "string"
    ~ properties.definition.parameters.webhookUrl.type:   "SecureString" => "securestring"


```

**Additional context**

**Comment by alex-frankel** [comment] 2020-05-11 14:44
Closing as duplicate of https://github.com/Azure/arm-template-whatif/issues/47

**Comment by slavizh** [comment] 2020-05-12 13:31
@alex-frankel not all the information is duplicate. This part is different in the already reported item:

```
 + properties.parameters.webhookUrl:

        value: "<webhook URL>"

    ~ properties.definition.parameters.customerName.type: "String" => "string"
    ~ properties.definition.parameters.tenantId.type:     "String" => "string"
    ~ properties.definition.parameters.timeZoneName.type: "String" => "string"
    ~ properties.definition.parameters.webhookUrl.type:   "SecureString" => "securestring"


```

**Comment by alex-frankel** [comment] 2020-05-12 14:54
ah, missed the case sensitivity noise. I will re-open

**Comment by alex-frankel** [comment] 2020-05-14 20:13
[w21?]

**Comment by alex-frankel** [comment] 2020-06-04 20:06
This fix should be fully deployed. Please let us know if you still see this issue.

**Closed by alex-frankel** 2020-06-04 20:06 UTC
Labels: fix committed, noise, property value casing
