### ISSUE TITLE
Subscription scope deployments don't track resources from modules correctly

### ISSUE THREAD

**Issue by mcalnd70** [Azure/arm-template-whatif#258] opened 2022-03-22 13:14 UTC
**Describe the bug**
Subscription scoped templates using modules to deploy resources isn't tracked correctly via the What-If outout

**To Reproduce**

Create x3 files
```
 \modules\mssa-random.bicep
mssubscriptionscope.bicep
mssubscriptionscope.parameters.json
```

**mssa-random.bicep** module (save to a subfolder called "modules")

```
param azsaprefix string
param azsalocation string
param azsasku string
param azsakind string

var storageaccount_randomname = '${toLower(azsaprefix)}${uniqueString(resourceGroup().id, deployment().name)}'

resource storageaccount 'Microsoft.Storage/storageAccounts@2021-08-01' = {
  name: storageaccount_randomname
  location: azsalocation
  sku: {
    name: azsasku
  }
  kind: azsakind
}
```

**mssubscriptionscope.bicep** file

```
targetScope = 'subscription'

param p_azresouregroup01 string
param p_azlocation string
param p_azsarandomprefix string

resource azresourcegroup01 'Microsoft.Resources/resourceGroups@2021-04-01' = {
  name: p_azresouregroup01
  location: p_azlocation
}

module storageaccount1 './modules/mssa-random.bicep' = {
  name: 'storageaccount1'
  scope: azresourcegroup01
  params: {
    azsaprefix: p_azsarandomprefix
    azsalocation: azresourcegroup01.location
    azsasku: 'Standard_LRS'
    azsakind: 'StorageV2'
  }
}

module storageaccount2 './modules/mssa-random.bicep' = {
  name: 'storageaccount2'
  scope: azresourcegroup01
  params: {
    azsaprefix: p_azsarandomprefix
    azsalocation: azresourcegroup01.location
    azsasku: 'Standard_LRS'
    azsakind: 'StorageV2'
  }
}
```

**mssubscriptionscope.parameters.json** file

```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "p_azlocation": {
      "value": "uksouth"
    },
    "p_azresouregroup01": {
      "value": "RG-Bicep"
    },
    "p_azsarandomprefix": {
      "value": "sabiceptst"
    }                          
  }
}
```

Step 1:  Run: `az deployment sub what-if --location uksouth --template-file .\mssubscriptionscope.bicep --parameters .\mssubscriptionscope.parameters.json`

```
Resource and property changes are indicated with this symbol:
  + Create

The deployment will update the following scope:

Scope: /subscriptions/{redacted}

  + resourceGroups/RG-Bicep [2021-04-01]

      apiVersion: "2021-04-01"
      id:         "/subscriptions/{redacted}/resourceGroups/RG-Bicep"
      location:   "uksouth"
      name:       "RG-Bicep"
      type:       "Microsoft.Resources/resourceGroups"

Resource changes: 1 to create.
```

Step 2: No mention on the What-If output about the Resources from Modules. Run to deploy the output in the What-If above and this will also deploy x2 Azure Storage Account resources:  `az deployment sub create --location uksouth --template-file .\mssubscriptionscope.bicep --parameters .\mssubscriptionscope.parameters.json`

Step 3: Run the What-If again - the What-If output identifies the x2 Azure Storage Accounts but are tagged as **IGNORE** and not **NO CHANGE** :  `az deployment sub what-if --location uksouth --template-file .\mssubscriptionscope.bicep --parameters .\mssubscriptionscope.parameters.json`

```
Resource and property changes are indicated with these symbols:
  = Nochange
  * Ignore

The deployment will update the following scopes

Scope: /subscriptions/{redacted}

  = resourceGroups/RG-Bicep [2021-04-01]

Scope: /subscriptions/{redacted}/resourceGroups/RG-Bicep

  * Microsoft.Storage/storageAccounts/sabiceptstkvllmcbo2souu
  * Microsoft.Storage/storageAccounts/sabiceptstr2gp4shllvvr4

Resource changes: 1 no change, 2 to ignore.

```

Step 4: I **deleted** the Storage Account **_sabiceptstr2gp4shllvvr4_** and re-run the What-If - same as Step 3: - It has no idea that the 2nd Storage Account should be provisioned again in the output here - although if you re-run the create command again it WILL put the Storage Account back into Azure.

```
Resource and property changes are indicated with these symbols:
  = Nochange
  * Ignore

The deployment will update the following scopes

Scope: /subscriptions/{redacted}

  = resourceGroups/RG-Bicep [2021-04-01]

Scope: /subscriptions/{redacted}/resourceGroups/RG-Bicep

  * Microsoft.Storage/storageAccounts/sabiceptstkvllmcbo2souu

Resource changes: 1 no change, 1 to ignore.
```

**Expected behavior**
Subscription scoped deployments should be tracked correctly in What-If when using modules deploying resources (this is an enforced design rule by Microsoft)

**Screenshots**
No screenshots - output listed above in the reproduction steps.

**Client** [e.g. PowerShell, CLI, API)
Azure CLI

**Additional context**
None

**Comment by stephaniezyen** [comment] 2022-04-26 22:59
Duplicate of #157

**Closed by stephaniezyen** 2022-04-26 22:59 UTC
Labels: Needs Triage :mag:
