### ISSUE TITLE
what-if doesn't show all resources in a new deployment with multiple modules

### ISSUE THREAD

**Issue by jcoliz** [Azure/arm-template-whatif#308] opened 2023-04-02 20:16 UTC
**Describe the bug**
My deployment deploys 4 resources. What-if only shows 2.

**To Reproduce**
1. Open Powershell
2. Make sure you're logged into Azure with the CLI, and have an active subscription
3. Follow the commands below. Note the `-w` switch on the last line

```
git clone -b topic/whatif-1 https://github.com/jcoliz/AzDeploy.Bicep
az group create --name whatif-1 --location "West US 2"
az deployment group create --name "WhatIf-$(Get-Random)" --resource-group whatif-1 --template-file .\AzDeploy.Bicep\Devices\iothub-dps-storage-upload.bicep -w
```

Result:

```
The deployment will update the following scope:

Scope: /subscriptions/768673ce-59ff-4109-9176-b8642424d38e/resourceGroups/whatif-1

  + Microsoft.Storage/storageAccounts/storage0003n4o2ni7ucvc6 [2022-09-01]

      apiVersion: "2022-09-01"
      id:         "/subscriptions/768673ce-59ff-4109-9176-b8642424d38e/resourceGroups/whatif-1/providers/Microsoft.Storage/storageAccounts/storage0003n4o2ni7ucvc6"
      kind:       "Storage"
      location:   "westus2"
      name:       "storage0003n4o2ni7ucvc6"
      sku.name:   "Standard_LRS"
      type:       "Microsoft.Storage/storageAccounts"

  + Microsoft.Storage/storageAccounts/storage0003n4o2ni7ucvc6/blobServices/default/containers/uploads [2022-09-01]

      apiVersion:              "2022-09-01"
      id:                      "/subscriptions/768673ce-59ff-4109-9176-b8642424d38e/resourceGroups/whatif-1/providers/Microsoft.Storage/storageAccounts/storage0003n4o2ni7ucvc6/blobServices/default/containers/uploads"
      name:                    "uploads"
      properties.publicAccess: "None"
      type:                    "Microsoft.Storage/storageAccounts/blobServices/containers"
```

**Expected behavior**

I expect all four resources in this deployment to be identified by the what-if invocation. Let's look at what happens when we actually deploy it:

```
az deployment group create --name "WhatIf-$(Get-Random)" --resource-group whatif-1 --template-file .\AzDeploy.Bicep\Devices\iothub-dps-storage-upload.bicep
```

```
    "outputResources": [
      {
        "id": "/subscriptions/768673ce-59ff-4109-9176-b8642424d38e/resourceGroups/whatif-1/providers/Microsoft.Devices/IotHubs/iothub-3n4o2ni7ucvc6",
        "resourceGroup": "whatif-1"
      },
      {
        "id": "/subscriptions/768673ce-59ff-4109-9176-b8642424d38e/resourceGroups/whatif-1/providers/Microsoft.Devices/provisioningServices/dps-3n4o2ni7ucvc6",
        "resourceGroup": "whatif-1"
      },
      {
        "id": "/subscriptions/768673ce-59ff-4109-9176-b8642424d38e/resourceGroups/whatif-1/providers/Microsoft.Storage/storageAccounts/storage0003n4o2ni7ucvc6",
        "resourceGroup": "whatif-1"
      },
      {
        "id": "/subscriptions/768673ce-59ff-4109-9176-b8642424d38e/resourceGroups/whatif-1/providers/Microsoft.Storage/storageAccounts/storage0003n4o2ni7ucvc6/blobServices/default/containers/uploads",
        "resourceGroup": "whatif-1"
      }
    ],
```

**Client** [e.g. PowerShell, CLI, API)

```
PS> az version
{
  "azure-cli": "2.43.0",
  "azure-cli-core": "2.43.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-devops": "0.20.0",
    "azure-iot": "0.18.3"
  }
}

PS> pwsh --version
PowerShell 7.2.9

PS> systeminfo
OS Name             : Microsoft Windows 10 Pro
OS Version          : 10.0.19045 N/A Build 19045
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Standalone Workstation
OS Build Type       : Multiprocessor Free
System Boot Time    : 4/1/2023, 9:07:34 AM
System Manufacturer : Gigabyte Technology Co., Ltd.
System Model        : B550I AORUS PRO AX
System Type         : x64-based PC
System Directory    : C:\Windows\system32
System Locale       : en-us;English (United States)
Hotfix(s)           : 18 Hotfix(s) Installed.,[01]: KB5022502,[02]: KB5000736,[03]: KB5012170,[04]: KB5015684,[05]:
                      KB5023696,[06]: KB5006753,[07]: KB5007273,[08]: KB5011352,[09]: KB5011651,[10]: KB5014032,[11]:
                      KB5014035,[12]: KB5014671,[13]: KB5015895,[14]: KB5016705,[15]: KB5018506,[16]: KB5020372,[17]:
                      KB5022924,[18]: KB5005699
```

**Comment by alex-frankel** [comment] 2023-04-11 15:58
Duplicate of #157

**Closed as completed by alex-frankel** 2023-04-11 15:58 UTC
Labels: Needs Triage :mag:

**Comment by jcoliz** [comment] 2023-04-11 16:20
@alex-frankel Thanks for having a look!
