### ISSUE TITLE
What-If blocks nested Management group deployment

### ISSUE THREAD

**Issue by SeSeicht** [Azure/arm-template-whatif#263] opened 2022-05-04 07:09 UTC
**Describe the bug**
When trying to deploy a nested Management-Group Structure with bicep What-IF an `AuthorizationFailed` occurs because it tries to `read` the not-existing Management Group.  

**To Reproduce**
Try to deploy a nested ( 3-Levels) Management-Group structure which doesn't exists before. 

**Expected behavior**
`AuthorizationFailed`
` MultipleErrorsOccurred - Long running operation failed with
     | status 'Failed'. Additional Info:'Multiple error occurred:
     | DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError. Please see details.' DeploymentWhatIfResourceError - The request to predict template deployment changes to scope '/providers/Microsoft.Management/managementGroups/XXX' has failed due to a resource error. See details for more information. AuthorizationFailed - The client 'XXX' with object id 'XXX' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/XXX' or the scope is invalid. If access was recently granted, please refresh your credentials. DeploymentWhatIfResourceError - The request to predict template deployment changes to scope '/providers/Microsoft.Management/managementGroups/XXX' has failed due to a resource error. See details for more information. AuthorizationFailed - The client 'XXX' with object id 'XXX' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/XXX' or the scope is invalid. If access was recently granted, please refresh your credentials. DeploymentWhatIfResourceError - The request to predict template deployment changes to scope '/providers/Microsoft.Management/managementGroups/XXX' has failed due to a resource error. See details for more information. AuthorizationFailed - The client 'XXX' with object id 'XXX' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/XXX' or the scope is invalid. If access was recently granted, please refresh your credentials. DeploymentWhatIfResourceError - The request to predict template deployment changes to scope '/providers/Microsoft.Management/managementGroups/XXX' has failed due to a resource error. See details for more information. AuthorizationFailed - The client 'XXX' with object id 'XXX' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/XXX' or the scope is invalid. If access was recently granted, please refresh your credentials. DeploymentWhatIfResourceError - The request to predict template deployment changes to scope '/providers/Microsoft.Management/managementGroups/XXX' has failed due to a resource error. See details for more information. AuthorizationFailed - The client 'XXX' with object id 'XXX' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/XXX' or the scope is invalid. If access was recently granted, please refresh your credentials. DeploymentWhatIfResourceError - The request to predict template deployment changes to scope '/providers/Microsoft.Management/managementGroups/XXX' has failed due to a resource error. See details for more information. AuthorizationFailed - The client 'XXX' with object id 'XXX' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/XXX' or the scope is invalid. If access was recently granted, please refresh your credentials.
`

**Screenshots**

**Client** [e.g. PowerShell, CLI, API)
`Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 5.202.0`

**Additional context**

**Comment by stephaniezyen** [comment] 2022-05-12 21:14
Duplicate of #162

**Closed by stephaniezyen** 2022-05-12 21:14 UTC
Labels: Needs Triage :mag:
