### ISSUE TITLE
Synapse adding roles to storage causing noise

### ISSUE THREAD

**Issue by mikeleuer** [Azure/arm-template-whatif#256] opened 2022-03-18 20:50 UTC
## Describe the noise
Synapse adding roles to storage causing noise
**Resource type**
Microsoft.Storage/storageAccounts + synapse

**apiVersion** 
Latest

**Client (PowerShell, Azure CLI, or API)**
Azure CLI

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

```
param location string = resourceGroup().location

param synStorageAccount string
param mainStorageAccount string 
param synStorageFileSys string

var synapseName = 'data-lake'

//https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles
var storage_blob_data_contributor = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')

resource synStorage 'Microsoft.Storage/storageAccounts@2021-04-01' existing = {
  name: synStorageAccount
}

resource synFileSystem 'Microsoft.Storage/storageAccounts/blobServices/containers@2021-04-01' existing = {
  name: synStorageFileSys
}

resource mainStorage 'Microsoft.Storage/storageAccounts@2021-04-01' existing = {
  name: mainStorageAccount
}

resource synapseWorkspace 'Microsoft.Synapse/workspaces@2021-06-01' = {
  name: synapseName
  tags: {
    DisplayName: 'Synapse Workspace'
    Environment: env
  }
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    defaultDataLakeStorage: {
      accountUrl: 'https://${synStorage.name}.dfs.${environment().suffixes.storage}'
      filesystem: synFileSystem.name
    }
    publicNetworkAccess: 'Enabled'
    managedResourceGroupName: '${group}-${env}-data-lake-sw-managed-rg'
  }

  resource synapseFirewall 'firewallRules@2021-06-01-preview' = {
      name: 'AllowAllWindowsAzureIps'
      properties: {
        startIpAddress: '0.0.0.0'
        endIpAddress: '0.0.0.0'
      }
  }
}

resource synapseWorkspaceFirewallRule1 'Microsoft.Synapse/workspaces/firewallrules@2021-03-01' = {
  parent: synapseWorkspace
  name: 'allowAll'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '255.255.255.255'
  }
}

resource roleAssignmentSynStorage1 'Microsoft.Authorization/roleAssignments@2020-10-01-preview' = {
  name: guid(resourceGroup().id, resourceId('Microsoft.Storage/storageAccounts', synStorage.name))
  properties: {
    principalId: synapseWorkspace.identity.principalId
    roleDefinitionId: storage_blob_data_contributor
  }
  scope: synStorage
}

resource roleAssignmentSynStorage2 'Microsoft.Authorization/roleAssignments@2020-10-01-preview' = {
  name: guid(resourceGroup().id, resourceId('Microsoft.Storage/storageAccounts', mainStorage.name))
  properties: {
    principalId: synapseWorkspace.identity.principalId
    roleDefinitionId: storage_blob_data_contributor
  }
  scope: mainStorage
}


output synapseWorkspaceName string = synapseWorkspace.name
output synapseDefaultStorageAccountName string = synStorage.name
output synapse_sql_pool_output object = {
  username: synapseWorkspace.properties.sqlAdministratorLogin
}



output synapse_identity_id string = synapseWorkspace.identity.principalId

```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No change
**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
```
  ~ Microsoft.Storage/storageAccounts/*************/providers/Microsoft.Authorization/roleAssignments/****** [2020-10-01-preview]
properties.principalId: "********-****-****-****-**********" => "[reference(resourceId('Microsoft.Synapse/workspaces', variables('synapseName')), '2021-06-01', 'full').identity.principalId]"
```

**Additional context**

**Comment by stephaniezyen** [comment] 2022-04-26 23:03
Duplicate of #202

**Closed by stephaniezyen** 2022-04-26 23:03 UTC
Labels: reference function, preflight improvement
