### ISSUE TITLE
Microsoft.Compute/VirtualMachines.properties.diagnosticsProfile.bootDiagnostics.storageUri

### ISSUE THREAD

**Issue by JustinGrote** [Azure/arm-template-whatif#79] opened 2020-05-31 22:45 UTC
## Describe the noise

**Resource type**
Microsoft.Compute/VirtualMachines

**apiVersion** (i.e. 2019-04-01)
2019-07-01

**Client (PowerShell, Azure CLI, or API)**
Powershell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
        "diagnosticsProfile": {
          "bootDiagnostics": {
            "enabled": true,
            "storageUri": "[
              reference(
                resourceId(
                  'Microsoft.Storage/storageAccounts', parameters('storageAccountName')
                )
              ).primaryEndpoints.blob
            ]"
          }
```

**Expected response
No noise once deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

![image](https://user-images.githubusercontent.com/15258962/83364307-3bdb5900-a355-11ea-84c2-ebea4b2511af.png)

**Additional context**
Doesn't appear to be resolving the reference prior to doing whatif comparison. It should resolve the reference prior to compare.

**Comment by alex-frankel** [comment] 2020-06-08 15:28
Closing as duplicate of #83

**Closed by alex-frankel** 2020-06-08 15:28 UTC
Labels: reference function
