### ISSUE TITLE
Microsoft.Insights/components (2015-05-01)

### ISSUE THREAD

**Issue by smokedlinq** [Azure/arm-template-whatif#48] opened 2020-04-27 12:28 UTC
## Describe the noise
Application Insights is reporting changes when no changes were made.

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Insights/components

**apiVersion** (i.e. 2019-04-01)
2015-05-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

```json
    {
      "type": "Microsoft.Insights/components",
      "name": "[variables('applicationInsightsName')]",
      "apiVersion": "2015-05-01",
      "location": "[resourceGroup().location]",
      "tags": "[variables('tags')]",
      "kind": "web",
      "properties": {
        "Name": "[variables('applicationInsightsName')]",
        "Application_Type": "web"
      }
    }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No changes

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
~ Microsoft.Insights/components/myappinsights [2015-05-01]
    - properties.publicNetworkAccessForIngestion: "Enabled"
    - properties.publicNetworkAccessForQuery:     "Enabled"
    - properties.Ver:                             "v2"
    + properties.Flow_Type:                       "Bluefield"
    + properties.Request_Source:                  "rest"
```

**Additional context**

**Comment by shenglol** [comment] 2020-04-27 17:18
Duplicate of https://github.com/Azure/arm-template-whatif/issues/14, but with a different API version. The fix for the resource type is under deployment. [w17]

**Comment by alex-frankel** [comment] 2020-04-30 20:10
The fix should be deployed. Please reopen the issue if you still see this noise.

**Closed by alex-frankel** 2020-04-30 20:10 UTC
Labels: duplicate, fix committed
