### ISSUE TITLE
az deployment sub what-if does not identity bastion resource, but after merging the pull request the bastion resource got provisioned.

### ISSUE THREAD

**Issue by ehsaneskandariboc** [Azure/arm-template-whatif#380] opened 2024-10-27 16:26 UTC
Bicep version
Bicep CLI v0.30.23

Describe the bug
What-if does not identity bastion resource, but after merging the pull request the bastion resource got provisioned.
Link to the Log:
https://github.com/Build-On-Clolud-Inc/landing-zone-hub-platform/actions/runs/11541876151/job/32124402219

To Reproduce
Link to the source code:
https://github.com/Build-On-Clolud-Inc/landing-zone-hub-platform/tree/sbx

Link to the github action YAML:
https://github.com/Build-On-Clolud-Inc/landing-zone-hub-platform/blob/sbx/.github/workflows/bicep-sbx-pipeline.yml

Additional context
Link to Az deploy:
https://github.com/Build-On-Clolud-Inc/landing-zone-hub-platform/actions/runs/11541889179/job/32124432298

Link to the deployment on azure:
https://portal.azure.com/#@buildoncloud.ca/resource/subscriptions/7a79e189-21f1-4bbc-b88e-e8e95784d59f/resourceGroups/rg-sbx-landingzone-eastus-01/deployments

**Comment by jeskew** [comment] 2024-11-06 16:32
Duplicate of #157 

The `bastion` module is not evaluated during what-if because runtime expressions are passed to it as parameters in [main.bicep](https://github.com/Build-On-Clolud-Inc/landing-zone-hub-platform/blob/9d0949ec1718b17f1156217f8364e91c9d6c9843/main.bicep#L93-L94). This will be addressed by the fix for #157

**Closed as not planned by jeskew** 2024-11-06 16:32 UTC

**Comment by ehsaneskandariboc** [comment] 2024-11-09 15:46
Seriously? After near four years for the other issue!
