### ISSUE TITLE
Noise with Microsoft.Web/sites@2021-01-15

### ISSUE THREAD

**Issue by JensKendl** [Azure/arm-template-whatif#212] opened 2021-08-13 07:52 UTC
## Describe the noise

**Resource type**: Microsoft.Web/sites

**apiVersion**: 2021-01-15

**Client** Azure CLI 2.27.1

**Relevant ARM Template code**
```
resource contactWeb 'Microsoft.Web/sites@2021-01-15' = {
  name: 'ase-${applicationName}-contacts-${environmentType}'
  location: location
  kind: 'app,linux'
  properties: {
    serverFarmId: serverFarm.id
    siteConfig: {
      linuxFxVersion: 'DOTNETCORE|3.1'
      http20Enabled: true
      alwaysOn: false
    }
  }
}
```

**Expected response**
I expected no noise since the template has not been modified since the resources were deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
  ~ Microsoft.Web/sites/ase-adc-contacts-dev [2021-01-15]
    + properties.siteConfig.localMySqlEnabled:   false
    + properties.siteConfig.netFrameworkVersion: "v4.6"

**Additional context**

**Comment by dallmair** [comment] 2021-11-05 16:42
We're seeing noise with the following properties:

* properties.siteConfig.appCommandLine
* properties.siteConfig.ftpsState
* properties.siteConfig.localMySqlEnabled
* properties.siteConfig.minTlsVersion
* properties.siteConfig.netFrameworkVersion
* properties.siteConfig.webSocketsEnabled

**Comment by ptemmer** [comment] 2021-11-08 19:19
So glad I found this. I was going nuts over apparent changes when executing what-if. I thought I did something wrong, yet I had no clue where they changes were coming from, as I didn't change the template in any way.

I add another one to the list:

* properties.siteConfig.use32BitWorkerProcess

**Comment by stephaniezyen** [comment] 2022-05-12 21:56
Duplicate of #265

**Closed by stephaniezyen** 2022-05-12 21:56 UTC
Labels: Needs Triage :mag:
