### ISSUE TITLE
Is there currently some problem with What-If service in West Europe?

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#129] opened 2020-09-17 11:42 UTC
Is there currently some problem with What-If service in West Europe?

**Comment by alex-frankel** [comment] 2020-09-18 15:21
apologies for missing this Stan - are you still seeing an issue?

**Comment by slavizh** [comment] 2020-09-21 12:05
No problem. It is preview and expected. I cannot tell as one of my co-workers was reporting that every time he tries to deploy error is returned. Worked with what-if disabled.

**Comment by alex-frankel** [comment] 2020-09-21 23:10
OK, I will close this, but if your co-worker can still repro, please re-open.

**Closed by alex-frankel** 2020-09-21 23:10 UTC

**Comment by simonhalby** [comment] 2020-09-24 07:11
I have a problem that might be related, all deployments stall in in the beginning and then fails because of time out. I first saw the problem yesterday, and still occurring today

**Comment by slavizh** [comment] 2020-09-24 07:52
@alex-frankel Can you check what is going on with the service? Is this may be the random issue that appears from time to time?

**Comment by alex-frankel** [comment] 2020-09-24 15:05
@simonhalby - is this timeout issue happening for what-if or for the actual deployment?

**Comment by simonhalby** [comment] 2020-09-24 15:21
@alex-frankel The problem seems to be gone right now, but it was for what -if as far as i can see.
"InternalServerError - Long running operation failed with status 'Failed'. Additional Info:'Encountered internal server error while processing the deployment what-if request"

**Comment by majastrz** [comment] 2020-09-25 18:20
@simonhalby and @slavizh can you share the correlation IDs from the internal server error? We found a transient issue affecting a tiny percentage of What-If requests and we have already started fixing it, but want to double check that this was the root cause.

**Comment by simonhalby** [comment] 2020-09-25 21:12
@majastrz I have a few correlation id as this happend a few times for me.
"3d36e202-3fde-4164-81e0-ec0a773ff887"
"50ce10b4-09eb-4121-a198-21a8f8290a4e"
"8eb4be62-4389-46cd-b5b0-70a4335d3154"

**Comment by majastrz** [comment] 2020-09-26 00:55
I checked our logs. There were two problems it seems:
1. The `union()` function in your template was failing at runtime due to the following error: "Type mismatch: Array vs. String". This seems like an issue with the template. Did you make changes to your template to make the error go away?
2. We have a bug in our error propagation that treated the evaluation failure as a server error instead of a client error. I created a task internally to fix this problem as well.

**Comment by simonhalby** [comment] 2020-09-26 06:58
I did fix the error there was on "50ce10b4-09eb-4121-a198-21a8f8290a4e","8eb4be62-4389-46cd-b5b0-70a4335d3154"
But i do not believe there was an error on "3d36e202-3fde-4164-81e0-ec0a773ff887"

**Comment by slavizh** [comment] 2020-09-28 06:20
The type mismatch even though it is issue on our end by providing the wrong configuration certainly can be improved by providing useful error that the end user can understand what is the problem.

**Comment by majastrz** [comment] 2020-09-28 19:01
@slavizh Yup. That is the problem number 2 that I mentioned above.
