### ISSUE TITLE
Microsoft.Network/trafficManagerProfiles priority marked for removal

### ISSUE THREAD

**Issue by fulder** [Azure/arm-template-whatif#111] opened 2020-08-10 13:57 UTC
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Network/trafficManagerProfiles

**apiVersion** (i.e. 2019-04-01)
2018-04-01

**Client (PowerShell, Azure CLI, or API)**
Azure CLI 2.10.1

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
{
  "type":"Microsoft.Network/trafficManagerProfiles",
  "apiVersion":"2018-04-01",
  "name":"myTrafficManager",
  "location":"global",
  "properties":{
    "profileStatus":"Enabled",
    "trafficRoutingMethod":"Performance",
    "dnsConfig":{
      "relativeName":"myTrafficManager",
      "ttl":60
    },
    "monitorConfig":{
      "profileMonitorStatus":"Enabled",
      "protocol":"HTTPS",
      "port":443,
      "path":"/health",
      "intervalInSeconds":30,
      "toleratedNumberOfFailures":3,
      "timeoutInSeconds":10
    },
    "endpoints":[
      {
        "id":"[concat(resourceId('Microsoft.Network/trafficManagerProfiles', 'myTrafficManager'), '/azureEndpoints/northeurope')]",
        "name":"northeurope",
        "type":"Microsoft.Network/trafficManagerProfiles/azureEndpoints",
        "properties":{
          "endpointStatus":"Enabled",
          "targetResourceId":"/subscriptions/<SUB_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Network/publicIPAddresses/<PUBLIC_IP_NAME>]",
          "target":"my.domain.examle.com",
          "endpointLocation":"North Europe"
        }
      }
    ],
    "trafficViewEnrollmentStatus":"Disabled",
    "maxReturn":0
  }
}
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No noise if the resource has already been created

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
```
~ Microsoft.Network/trafficManagerProfiles/myTrafficManager [2018-04-01]
    ~ properties.endpoints: [
      ~ 0:
        - properties.priority:         1
```
**Additional context**
As priority is an optional argument the `what-if` command should maybe ignore this if the `trafficRoutingMethod` is not `Pirority`

**Comment by shenglol** [comment] 2020-10-15 19:34
[w40].

**Comment by alex-frankel** [comment] 2020-10-15 19:53
This fix should be full deployed. Let us know if you are still seeing the issue.

**Comment by fulder** [comment] 2020-10-20 13:48
I have tried to run `what-if` for this template today and it looks like this noise is still present.

**Comment by shenglol** [comment] 2020-10-20 17:00
Investigating...

**Comment by shenglol** [comment] 2020-10-21 23:29
Found the cause and fixed it again. Waiting on deployment.

**Comment by alex-frankel** [comment] 2020-10-22 17:18
Week?

**Comment by shenglol** [comment] 2020-10-22 17:22
[w44]?

**Comment by alex-frankel** [comment] 2020-12-03 22:01
@shenglol - can we confirm this went out in w44

**Comment by alex-frankel** [comment] 2021-01-25 06:45
This fix has been deployed. Please let us know if you still see the issue.

**Closed by alex-frankel** 2021-01-25 06:45 UTC
Labels: defaults, fix committed

**Comment by fulder** [comment] 2021-01-26 14:15
Looks good to me! :) Seems like this noise is no longer present. Thank you for this fix :+1:
